const regionData = {
  "Western Africa": [
    "Benin",
    "Burkina Faso",
    "Cape Verde",
    "Cote d'Ivoire (Ivory Coast)",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Liberia",
    "Mali",
    "Mauritania",
    "Niger",
    "Nigeria",
    "Senegal",
    "Sierra Leone",
    "Togo",
  ],
  "Central Africa": [
    "Angola",
    "Burundi",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Congo (Democratic Republic of the Congo)",
    "Congo (Republic of the Congo)",
    "Equatorial Guinea",
    "Gabon",
    "Sao Tome and Principe",
  ],
  "Eastern Africa": [
    "Burundi",
    "Comoros",
    "Djibouti",
    "Eritrea",
    "Ethiopia",
    "Kenya",
    "Madagascar",
    "Malawi",
    "Mauritius",
    "Mozambique",
    "Rwanda",
    "Seychelles",
    "Somalia",
    "South Sudan",
    "Tanzania",
    "Uganda",
    "Zambia",
    "Zimbabwe",
  ],
  "Northern Africa": [
    "Algeria",
    "Egypt",
    "Libya",
    "Mauritania",
    "Morocco",
    "Sudan",
    "Tunisia",
    "Western Sahara",
  ],
  "Southern Africa": [
    "Botswana",
    "Eswatini",
    "Lesotho",
    "Namibia",
    "South Africa",
  ],
  "Australia and New Zealand": ["Australia", "New Zealand"],
  Melanesia: ["Fiji", "Papua New Guinea", "Solomon Islands", "Vanuatu"],
  Micronesia: [
    "Federated States of Micronesia",
    "Kiribati",
    "Marshall Islands",
    "Nauru",
    "Palau",
  ],
  Polynesia: ["Samoa", "Tonga", "Tuvalu"],
  "Central America": [
    "Belize",
    "Costa Rica",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Nicaragua",
    "Panama",
  ],
  "Latin America and Caribbean": [
    "Argentina",
    "Bahamas",
    "Barbados",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "Haiti",
    "Jamaica",
    "Mexico",
    "Peru",
    "Trinidad and Tobago",
    "Uruguay",
    "Venezuela",
  ],
  "North America": ["Canada", "United States", "Mexico"],
  "South America": [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay",
    "Venezuela",
  ],
  "Central Asia": [
    "Kazakhstan",
    "Kyrgyzstan",
    "Tajikistan",
    "Turkmenistan",
    "Uzbekistan",
  ],
  "Eastern Asia": ["China", "Japan", "North Korea", "South Korea", "Mongolia"],
  "Southeastern Asia": [
    "Brunei",
    "Cambodia",
    "Indonesia",
    "Laos",
    "Malaysia",
    "Myanmar",
    "Philippines",
    "Singapore",
    "Thailand",
    "Timor-Leste",
    "Vietnam",
  ],
  "Southern Asia": [
    "Afghanistan",
    "Bangladesh",
    "Bhutan",
    "India",
    "Maldives",
    "Nepal",
    "Pakistan",
    "Sri Lanka",
  ],
  "Western Asia": [
    "Armenia",
    "Azerbaijan",
    "Bahrain",
    "Cyprus",
    "Georgia",
    "Iran",
    "Iraq",
    "Israel",
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Oman",
    "Palestine",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "Turkey",
    "United Arab Emirates",
    "Yemen",
  ],
  "Eastern Europe": [
    "Belarus",
    "Bulgaria",
    "Czech Republic",
    "Hungary",
    "Moldova",
    "Poland",
    "Romania",
    "Russia",
    "Slovakia",
    "Ukraine",
  ],
  "Northern Europe": [
    "Denmark",
    "Estonia",
    "Finland",
    "Iceland",
    "Ireland",
    "Latvia",
    "Lithuania",
    "Norway",
    "Sweden",
    "United Kingdom",
  ],
  "Southern Europe": [
    "Albania",
    "Andorra",
    "Bosnia and Herzegovina",
    "Croatia",
    "Greece",
    "Italy",
    "Malta",
    "Montenegro",
    "North Macedonia",
    "Portugal",
    "San Marino",
    "Serbia",
    "Slovenia",
    "Spain",
    "Vatican City",
  ],
  "Western Europe": [
    "Austria",
    "Belgium",
    "France",
    "Germany",
    "Liechtenstein",
    "Luxembourg",
    "Monaco",
    "Netherlands",
    "Switzerland",
  ],
};



export default regionData ;
