const geopoliticalData = {
    "Arab World": [
      "Algeria",
      "Bahrain",
      "Comoros",
      "Djibouti",
      "Egypt",
      "Iraq",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Libya",
      "Mauritania",
      "Morocco",
      "Oman",
      "Palestine",
      "Qatar",
      "Saudi Arabia",
      "Somalia",
      "Sudan",
      "Syria",
      "Tunisia",
      "United Arab Emirates",
      "Yemen",
    ],
    "Asia-Pacific Economic Cooperation (APEC)": [
      "Australia",
      "Brunei",
      "Canada",
      "Chile",
      "China",
      "Hong Kong",
      "Indonesia",
      "Japan",
      "Malaysia",
      "Mexico",
      "New Zealand",
      "Papua New Guinea",
      "Peru",
      "Philippines",
      "Russia",
      "Singapore",
      "South Korea",
      "Taiwan",
      "Thailand",
      "United States",
      "Vietnam",
    ],
    "Association of Southeast Asian Nations (ASEAN)": [
      "Brunei",
      "Cambodia",
      "Indonesia",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Philippines",
      "Singapore",
      "Thailand",
      "Vietnam",
    ],
    Balkans: [
      "Albania",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Kosovo",
      "Montenegro",
      "North Macedonia",
      "Romania",
      "Serbia",
      "Slovenia",
    ],
    BRICS: ["Brazil", "Russia", "India", "China", "South Africa"],
    "Common Market for Eastern and Southern Africa (COMESA)": [
      "Burundi",
      "Comoros",
      "Democratic Republic of the Congo",
      "Djibouti",
      "Egypt",
      "Eswatini",
      "Ethiopia",
      "Kenya",
      "Libya",
      "Madagascar",
      "Malawi",
      "Mauritius",
      "Rwanda",
      "Seychelles",
      "Somalia",
      "Sudan",
      "Tanzania",
      "Uganda",
      "Zambia",
      "Zimbabwe",
    ],
    "Commonwealth Of Independent States (CIS)": [
      "Armenia",
      "Azerbaijan",
      "Belarus",
      "Kazakhstan",
      "Kyrgyzstan",
      "Moldova",
      "Russia",
      "Tajikistan",
      "Turkmenistan",
      "Ukraine",
      "Uzbekistan",
    ],
    "Economic Community of West African States (ECOWAS)": [
      "Benin",
      "Burkina Faso",
      "Cabo Verde",
      "Cote d'Ivoire",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Niger",
      "Nigeria",
      "Senegal",
      "Sierra Leone",
      "Togo",
    ],
    "European Union (EU)": [
      "Austria",
      "Belgium",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Netherlands",
      "Poland",
      "Portugal",
      "Romania",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
    ],
    G20: [
      "Argentina",
      "Australia",
      "Brazil",
      "Canada",
      "China",
      "France",
      "Germany",
      "India",
      "Indonesia",
      "Italy",
      "Japan",
      "Mexico",
      "Russia",
      "Saudi Arabia",
      "South Africa",
      "South Korea",
      "Turkey",
      "United Kingdom",
      "United States",
    ],
    "Gulf Cooperation Council (GCC)": [
      "Bahrain",
      "Kuwait",
      "Oman",
      "Qatar",
      "Saudi Arabia",
      "United Arab Emirates",
    ],
    "Gulf Countries": [
      "Bahrain",
      "Kuwait",
      "Oman",
      "Qatar",
      "Saudi Arabia",
      "United Arab Emirates",
    ],
    "Middle East": [
      "Bahrain",
      "Iran",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Oman",
      "Palestine",
      "Qatar",
      "Saudi Arabia",
      "Syria",
      "United Arab Emirates",
      "Yemen",
    ],
    "Middle East and North Africa (MENA)": [
      "Algeria",
      "Bahrain",
      "Egypt",
      "Iran",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Libya",
      "Morocco",
      "Oman",
      "Palestine",
      "Qatar",
      "Saudi Arabia",
      "Sudan",
      "Syria",
      "Tunisia",
      "United Arab Emirates",
      "Yemen",
    ],
    "South Asian Association for Regional Cooperation (SAARC)": [
      "Afghanistan",
      "Bangladesh",
      "Bhutan",
      "India",
      "Maldives",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
    ],
  };